
services:
  redis:
    image: redis:7
    container_name: redis-logs
    ports:
      - "6370:6379"

  api-server:
    build: ./api-server
    container_name: api-server
    ports:
      - "9000:9000"
      - "9002:9002"
    environment:
      REDIS_URL: redis://redis:6379
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      S3_BUCKET: ${S3_BUCKET}
      
    depends_on:
      - redis




# services:
#   redis:
#     image: redis:7
#     container_name: redis-logs-shyam-123
#     ports:
#       - "6370:6379"

#   build-server:
#     build: .
#     container_name: build-server
#     depends_on:
#       - redis
#     environment:
#       REDIS_URL: redis://redis:6379
#       PROJECT_ID: demo123

